### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by romatou18** [Bizarrus/N26-Leaks#1]
Hi,

I was wondering where this information is coming from as there is no reliable or official source mentioned ? Is it your own experience with this bank ? I was looking at opening an online bank account in the Euro zone being an expat, and trying to choose a bank  but this is not easy.

I am not looking for anything fancy but just reliable, and that allows me to open a bank account without being on site at home in Europe.

Cheers.

**Comment by Bizarrus** [comment]
Surely it is logical that when we speak of a "leak" here, we are talking about inside information and not our own feelings.  Accordingly, this information is not officially published by the operator.

I'm surprised, why you ask these questions.

A bank account in the European Union has requirements, including that the applicant for the account must work or reside within the European Union or represent a company within the EU as defined by law.

Furthermore, I find it amusing that the content is understood, which is written in German but corresponds in English.

**Comment by romatou18** [comment]
- This is copy and paste content nit even a proper photo of an official document. This is why I'm asking the question,  there's no proof of the authenticity, anyone could write this therefore, and "obviously" this is not obvious.
- Google translate is handy, all i can say in German is Ein beer bitte.
- Yes a bank should have a proof of residency from the applicant, that must reside in the EU, but no by law thw applicant does not have to work in the EU, being an expatriate I have a bank account in my home country while working in another country. This is legal.

**Comment by Bizarrus** [comment]
What is the difference between plain text or an PDF-based document? Both can be copy & pasted. Must all insider informations contains a copy of an real/official document? Must all insider informations contains an name of the insider? Did you leak some informations about your company with your name?

> [...] being an expatriate I have a bank account in my home country while working in another country. This is legal.

Sure, that's legal. If you operate within the EU, thats legal. But if you live and work outside the EU and would like to open a bank account within the EU, any bank can and will refuse you. 

You have a powerful tool:  The Internet.  You can find all this out for yourself, it's all in the EU laws and guidelines for European member states.

The information available here has nothing to do with the fact that your bank accounts within the EU have not been approved.

Nor will I disclose at any time where the inside information came from.  This information has been checked by me personally through the shoulder glance of the insider, without documents.

I will close these issue.
